#!/usr/bin/env python3
"""Reproducibly compile the API-neutral Header platform Java sources into patch Smali."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "patches/java/com/google/android/inputmethod/pinyin/headerplatform"
OUTPUT_DIR = ROOT / "patches/smali/headerplatform"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--android-jar", type=Path, required=True)
    parser.add_argument("--jdk", type=Path, required=True)
    parser.add_argument("--build-tools", type=Path, required=True)
    parser.add_argument("--apktool", type=Path, required=True)
    args = parser.parse_args()

    android_jar = args.android_jar.resolve()
    jdk = args.jdk.resolve()
    javac = jdk / "bin/javac.exe"
    jar = jdk / "bin/jar.exe"
    d8 = args.build_tools.resolve() / "d8.bat"
    apktool = args.apktool.resolve()
    sources = sorted(
        path for path in SOURCE_DIR.glob("*.java")
        if path.name != "ClipboardHeaderModule.java"
    )
    for path in [android_jar, javac, jar, d8, apktool, *sources]:
        if not path.exists():
            raise FileNotFoundError(path)

    environment = os.environ.copy()
    environment["JAVA_HOME"] = str(jdk)
    environment["PATH"] = str(jdk / "bin") + os.pathsep + environment.get("PATH", "")

    with tempfile.TemporaryDirectory(prefix="header-platform-smali-") as temporary:
        root = Path(temporary)
        classes = root / "classes"
        dex = root / "dex"
        decoded = root / "decoded"
        classes.mkdir()
        dex.mkdir()
        feedback_stub = root / "stubs/com/google/android/inputmethod/pinyin/InlineAutofillFeedbackCompat.java"
        feedback_stub.parent.mkdir(parents=True)
        feedback_stub.write_text(
            "package com.google.android.inputmethod.pinyin;\n"
            "public final class InlineAutofillFeedbackCompat {\n"
            "  public static void perform(android.view.View view) {}\n"
            "}\n",
            encoding="utf-8",
        )
        subprocess.run(
            [str(javac), "-source", "7", "-target", "7",
             "-bootclasspath", str(android_jar), "-d", str(classes),
             *[str(path) for path in sources], str(feedback_stub)],
            check=True,
            env=environment,
        )
        compiled_jar = root / "header-platform.jar"
        subprocess.run(
            [str(jar), "cf", str(compiled_jar), "-C", str(classes), "."],
            check=True,
            env=environment,
        )
        subprocess.run(
            [str(d8), "--min-api", "17", "--lib", str(android_jar),
             "--output", str(dex), str(compiled_jar)],
            check=True,
            env=environment,
        )
        tiny_apk = root / "header-platform.apk"
        with zipfile.ZipFile(tiny_apk, "w", zipfile.ZIP_STORED) as archive:
            archive.write(dex / "classes.dex", "classes.dex")
        subprocess.run(
            [str(jdk / "bin/java.exe"), "-jar", str(apktool), "d", "-f",
             str(tiny_apk), "-o", str(decoded)],
            check=True,
            env=environment,
        )
        generated = decoded / "smali/com/google/android/inputmethod/pinyin/headerplatform"
        if not generated.is_dir():
            raise RuntimeError(f"Generated Header platform Smali missing: {generated}")
        if OUTPUT_DIR.exists():
            shutil.rmtree(OUTPUT_DIR)
        shutil.copytree(generated, OUTPUT_DIR)

    # ClipboardHeaderModule depends on a legacy ClipboardCandidateCompat API and
    # is therefore generated by a separate stub-backed compiler. It is still a
    # mandatory runtime module: regenerate it atomically after replacing the
    # platform output directory so a platform refresh cannot silently delete it.
    clipboard_generator = ROOT / "scripts/generate_clipboard_header_module_smali.py"
    subprocess.run(
        [sys.executable, str(clipboard_generator),
         "--android-jar", str(android_jar),
         "--jdk", str(jdk),
         "--build-tools", str(args.build_tools.resolve()),
         "--apktool", str(apktool)],
        check=True,
        env=environment,
    )

    print(f"Generated {len(list(OUTPUT_DIR.glob('*.smali')))} Header platform Smali files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
