#!/usr/bin/env python3
"""Resolve the one verified legacy/Compose resource declaration collision.

AndroidX Core and the bundled legacy support resources define the same fontStyle
attribute with identical normal/italic enum values. AAPT2 rejects the duplicate
enum body after resource merging. Removing the standalone legacy declaration and letting AndroidX Core provide the
canonical declaration preserves the stable resource ID and both enum values
without deleting unrelated resources. The legacy APK's compiled styleable arrays
remain in its DEX and are not regenerated by this operation.
"""

from __future__ import annotations

import argparse
from pathlib import Path


LEGACY = """    <attr name=\"fontStyle\">\n        <enum name=\"normal\" value=\"0\" />\n        <enum name=\"italic\" value=\"1\" />\n    </attr>"""
REFERENCE = ""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("decoded", type=Path)
    args = parser.parse_args()
    attrs = args.decoded / "res" / "values" / "attrs.xml"
    text = attrs.read_text(encoding="utf-8")
    count = text.count(LEGACY)
    if count != 1:
        raise RuntimeError(f"expected exactly one canonical fontStyle block, found {count}")
    attrs.write_text(text.replace(LEGACY, REFERENCE), encoding="utf-8", newline="\n")
    print(f"normalized legacy fontStyle declaration in {attrs}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
